# OpenAI API key
OPENAI_API_KEY = "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"
